apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vgmp9x3an-python 
  janus-idp.io/tekton: vgmp9x3an-python
  backstage.io/kubernetes-id: vgmp9x3an-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vgmp9x3an-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml