apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vgmp9x3an-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vgmp9x3an-python 
  name: vgmp9x3an-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vgmp9x3an-python 
